name: Publish TechDocs Site

on:
  push:
    branches: [main]
    # You can even set it to run only when TechDocs related files are updated.
    paths:
      - "docs/**"
      - "onboarding/**"
      - "mkdocs.yml"
      - ".github/workflows/main.yml"
      - "app-doc.yaml"

jobs:
  publish-techdocs-site:
    runs-on: ubuntu-latest

    env:
      TECHDOCS_BUCKET_NAME: "tech-docs-documents"
      ENTITY_NAMESPACE: "default"
      ENTITY_KIND: "Component"
      ENTITY_NAME: "app-doc"

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.9"
      - uses: google-github-actions/setup-gcloud@v0.2.1
        with:
          version: "290.0.1"
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true
      - uses: cloudbees/plantuml-github-action@master
      
      - name: Install techdocs-cli
        run: sudo npm install -g @techdocs/cli@0.3.7

      - name: Install mkdocs and mkdocs plugins
        run: |
          python -m pip install mkdocs-material==7.1.5 mkdocs-git-authors-plugin==0.3.3  mkdocs-exclude==1.0.2 mkdocs-same-dir==0.1.0

      - name: Generate docs site
        run: techdocs-cli generate --verbose --no-docker

      - name: Publish docs site
        run: techdocs-cli publish --publisher-type googleGcs --storage-name
          $TECHDOCS_BUCKET_NAME --entity
          $ENTITY_NAMESPACE/$ENTITY_KIND/$ENTITY_NAME
